name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: diggerhq/digger@v0.4.0
        with:
          target: my-target
          backend: gcs
          bucket: my-terraform-bucket-27
          prefix: terraform-bucket-27
